"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true

[username]
style_user = "bold blue"
format = "[$user]($style) in "
show_always = true

[hostname]
ssh_only = false
format = "[$hostname]($style)\n"
style = "bold dimmed blue"
disabled = false

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '

[aws]
symbol = "  "

[azure]
symbol = " "

[bun]
symbol = " "

[c]
symbol = " "

[character]
success_symbol = "[➜](bold green)"
error_symbol = "[➜](bold red)"

[cmake]
symbol = " "

[container]
symbol = " "

[cpp]
symbol = " "

[dart]
symbol = " "

[deno]
symbol = " "

[directory]
read_only = "󰌾 "
truncation_length = 5
format = "[$path]($style)[$lock_symbol]($lock_style) "

[docker_context]
symbol = " "

[dotnet]
symbol = ".NET "

[elixir]
symbol = " "

[elm]
symbol = " "

[erlang]
symbol = " "

[gcloud]
symbol = "󱇶 "

[git_branch]
symbol = " "

[golang]
symbol = "󰟓 "

[gradle]
symbol = " "

[haskell]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[kotlin]
symbol = " "

[kubernetes]
symbol = " "

[lua]
symbol = " "

[nim]
symbol = " "

[nix_shell]
symbol = "󱄅 "

[nodejs]
format = "via [ Node.js $version](bold green) "
detect_files = ["package.json", ".node-version"]
detect_folders = ["node_modules"]

[ocaml]
symbol = " "

[package]
symbol = " "

[perl]
symbol = " "

[php]
symbol = " "

[python]
symbol = " "
pyenv_version_name = true
format = 'via [${symbol}python (${version} )(\($virtualenv\) )]($style)'
style = "bold yellow"
pyenv_prefix = "venv "
python_binary = ["./venv/bin/python", "python", "python3", "python2"]
detect_extensions = ["py"]
version_format = "v${raw}"

[rlang]
symbol = " "

[ruby]
symbol = " "

[rust]
symbol = " "

[scala]
symbol = " "

[swift]
symbol = " "

[typst]
symbol = "t "

[zig]
symbol = " "
