# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

# Replace the "❯" symbol in the prompt with "➜"
[character] # The name of the module we are configuring is "character"
success_symbol = "[➜](bold green)" # The "success_symbol" segment is being set to "➜" with the color "bold green"
error_symbol = "[➜](bold red)"

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[directory]
read_only = " "
truncation_length = 5
format = "[$path]($style)[$lock_symbol]($lock_style) "

[username]
style_user = "bold blue"
format = "[$user]($style) in "
show_always = true

[hostname]
ssh_only = false
format = "[$hostname]($style)\n"
trim_at = "-"
style = "bold dimmed blue"
disabled = false

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '
